; Boxgirl is a debug sprite. She mostly fills out a proper 16x32 area, and is approximately
; the planned size for player characters and taller enemies. Her animation is extremely minimal
; while still maintaining a separate visual state for all 4 cardinal directions.

.import boxgirl_anim_idle_right, boxgirl_anim_idle_left
.import boxgirl_anim_move_right, boxgirl_anim_move_left, boxgirl_anim_move_down, boxgirl_anim_move_up
.import boxgirl_anim_swim_right, boxgirl_anim_swim_left, boxgirl_anim_swim_down, boxgirl_anim_swim_up
.import boxgirl_anim_underwater_right, boxgirl_anim_underwater_left, boxgirl_anim_underwater_down, boxgirl_anim_underwater_up
.import boxgirl_anim_teleport