.global FAR_initialize_actions
.global FAR_draw_ability_icon_immediate, FAR_draw_ability_icon_buffered
.global FAR_draw_ability_icon_buffered_top_row, FAR_draw_ability_icon_buffered_bottom_row

.global action_memory
.global actionset_a
.global actionset_b
.global actionset_c
.global action_inventory

ACTION_NONE = 0

; Implemented
ACTION_DASH = 1
ACTION_JUMP = 2

; Unimplemented
ACTION_FEATHER = 3
ACTION_FIRE = 4
ACTION_HAMMER = 5

