.global refresh_palettes
.global refresh_palettes_gameloop
.global BgPaletteDirty
.global ObjPaletteDirty
.global BgPaletteBuffer
.global ObjPaletteBuffer
.global HudPaletteBuffer
.global Brightness
.global HudPaletteActive
.global HudGradientBuffer

.global set_brightness
.global init_hud_palette
.global refresh_palettes_lag_frame
.global queue_arbitrary_bg_palette
.global queue_arbitrary_obj_palette